services:
  - type: web
    name: ai-assistant-backend
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: SESSION_COOKIE_NAME
        value: __session
      - key: SESSION_EXPIRES_IN
        value: 432000000
      - key: MCP_SERVER_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
