services:
  - type: web
    name: ai-assistant-mcp-server
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements-prod.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: ELASTICSEARCH_ENDPOINT
        sync: false
      - key: ELASTICSEARCH_API_KEY
        sync: false
